### ISSUE TITLE
Read, sign, and return an Invention Agreement

### ISSUE THREAD

**Issue by burrage** [curiouslearning/workshop_drag_into_place_1#3]
You may have completed this task already from the pre-workshop e-mail-- move to "Done" if so!

---------

Read the [Invention Agreement](https://docs.google.com/document/d/1BHNxggUfVBXfTT7M0jHVkguy1DLyED8PPHNPQy6s42c/edit?usp=sharing).

If you have questions regarding the agreement, please read the [Licensing FAQ](https://docs.google.com/document/d/1Q-ByHTYuoUsamhQcaHboyffCtBNu62j-0UkdVGtkqtI/edit?usp=sharing), and contact the course PM @bburrage on Slack if you have any further questions or concerns.

When you’re ready to sign and return: 

- In Google Docs, select “File” -> “Make A Copy” to save it to your Google Drive.
- Fill out your name and address marked in blue and digitally sign where it says “Workshop Participant”.
- Copy a link to the signed document and comment with the link below.

**Comment by burrage** [comment]
@Vishwaksen 

Would it be possible to sign the bottom "Participant" line with your signature?

Suggestions for digitally signing:

1.) Download the document as a PDF and use a PDF editing program like Adobe Acrobat Pro to draw a signature.

You can also do this in Microsoft Word if you have that by going to "Insert" -> "Shapes" and choosing the last option in the "Lines section", the squiggly line, called "Scribble". The cursor will turn to a plus symbol and you can sign that way.

OR

2.) Low-tech but still works! Sign a piece of paper and take a photo of it with a cellphone. Transfer the photo to your computer and crop the signature. In the Google Doc, insert the photo where the signature line should go.

If you have any questions or need further help, please let me know. Thanks!

**Comment by Vishwaksen** [comment]
The updated agreement as per above requirements is available at : https://drive.google.com/file/d/0B-ue1kjt09ewTzBCVmdaNXczUjA/view?usp=sharing
